name: "validate Kong image (targeted)"
run-name: "validate Kong ${{ format('{0}:{1}', github.event.inputs.kong-image-repo, github.event.inputs.kong-image-tag) }}"

on:
  workflow_dispatch:
    inputs:
      kong-image-repo:
        description: Kong Gateway Docker image to test with (repository).
        type: string
        required: true
        default: "kong/kong-gateway"
      kong-image-tag:
        description: Kong Gateway Docker image to test with (tag).
        type: string
        required: true
        default: "latest"
      e2e-controller-image-repo:
        description: KIC Docker image for E2E tests (repository).
        type: string
        required: true
        default: "kong/kubernetes-ingress-controller"
      e2e-controller-image-tag:
        description: KIC Docker image for E2E tests (tag).
        type: string
        required: true
        default: "latest"
      issue-number:
        description: Issue number to post a comment in. If empty, no comment is posted.
        type: string
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "this is a test"
