name: "validate Kong image (targeted)"
run-name: "validate Kong ${{ format('{0}:{1}', github.event.inputs.kong-image-repo, github.event.inputs.kong-image-tag) }}"

on:
  workflow_dispatch:
    inputs:
      kong-image-repo:
        description: Kong Gateway Docker image to test with (repository).
        type: string
        required: true
        default: "kong/kong-gateway"
      kong-image-tag:
        description: Kong Gateway Docker image to test with (tag).
        type: string
        required: true
        default: "latest"
      e2e-controller-image-repo:
        description: KIC Docker image for E2E tests (repository).
        type: string
        required: true
        default: "kong/kubernetes-ingress-controller"
      e2e-controller-image-tag:
        description: KIC Docker image for E2E tests (tag).
        type: string
        required: true
        default: "latest"
      issue-number:
        description: Issue number to post a comment in. If empty, no comment is posted.
        type: string
        required: false

jobs:
  run-e2e-tests:
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/_e2e_tests.yaml
    secrets: inherit
    with:
      kic-image: ${{ format('{0}:{1}', github.event.inputs.e2e-controller-image-repo, github.event.inputs.e2e-controller-image-tag) }}
      kong-image: ${{ format('{0}:{1}', github.event.inputs.kong-image-repo, github.event.inputs.kong-image-tag) }}
      load-local-image: false
      run-gke: true
      run-istio: true
      all-supported-k8s-versions: true
